### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by dreamsindrums** [linuxserver/docker-webgrabplus#13]
Needs an upgrade to the latest beta for encryption support.

**Comment by tobbenb** [comment]
I'll have a look at it.

**Comment by tobbenb** [comment]
@dreamsindrums This was closed by #14

**Comment by DOFfactory** [comment]
any chance to upgrade to v2.1.11, I am receiving recently a lot of timed-out errors while updating ... the current version is v.2.1.9

> Release notes: 
> added : check and log of subpage headerlist values errors (only integers, no 0, not > number of headers sets)
> added : default subpage headerlist {list|} which ignores all header sets except the first one
> **fixed : bug in url file mode , must start with // or file:// (was \\)**
> added : option to use a global element in a subpage.format {list|'global_element'}
> **new : grabengine overhaul, completely rewritten.
 It solves the problem of save and reload of cookies, e.g. in method POST-BACK**
> new : temporary re-introduction of grabengine as sitedependant element
> added : new grabengine supports 'Brotli' compressed stream decompression
> fixed : method=POST was not overwritten with later methods with other value
> fixed : if no headers specified , always take the defaults
