### ISSUE TITLE
Setup documentation guide link is broken

### ISSUE THREAD

**Issue by Darren-Hill** [linuxserver/docker-webgrabplus#16]
Just a quick heads-up that the set-up guide link in the README.md tab here is broken (in the application set-up section):

"To configure WebGrab+Plus follow the [guide][guideurl]"

Should it point to the URL below?

http://webgrabplus.com/documentation/configuration/howto

**Comment by tobbenb** [comment]
Thanks for the info. I'll fix it.
It was overlooked when we moved to our new pipeline builder.

**Comment by tobbenb** [comment]
Fixed now.
