### ISSUE TITLE
System error on Synology NAS

### ISSUE THREAD

**Issue by tdse13** [linuxserver/docker-webgrabplus#19]
docker-webgrabplus stops with a system error. I just upgrades to the lastest docker version available for DSM  (18.09.6). Everything else seems to be OK. A manual update runs smoothly. Therefore, I assume it's an issue with the docker-webgrabplus container. Any solution? Thank you.

**Comment by j0nnymoe** [comment]
We've had reports of the latest version of docker has issues and users have had to roll back. Unfortunately we don't own any Synology hardware within the team so we are unable to diagnose/troubleshoot this issue.

**Comment by CHBMB** [comment]
Without logs or anything else I am going to close this and assume it's an upstream issue with the Synology docker/docker compose recent update
