### ISSUE TITLE
Grabbing doesn't start

### ISSUE THREAD

**Issue by B0ndo2** [linuxserver/docker-webgrabplus#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I am running on RHEL 7.9, I configured wg-cron appropriately. Grabbing doesn't start, checking the logs I see the message below at expected run time.
Cannot make/remove an entry for the specified session
I modified the running container (I know it is not persistent) as follows:
sed -i '/session    required     pam_loginuid.so/c\#session    required   pam_loginuid.so' /etc/pam.d/cron
Now it works, can you fix this in the image ?

------------------------------

## Expected Behavior

Run on specified time
## Current Behavior

Does not run and throws error in the log 
Cannot make/remove an entry for the specified session

## Environment
**OS: RHEL 7.9
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container
podman run -d \
  --name=webgrabplus \
  -e PUID=1001 \
  -e PGID=1001 \
  -e TZ=America/New_York \
  -v /home/wgplus:/config \
  -v /home/wgplus:/data \
  ghcr.io/linuxserver/webgrabplus

##Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...
[s6-init] ensuring user provided files have correct perms...
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
******** Please use the file wg3-cron to adjust the scheduled time for running WebGrab++. wg-cron can now be deleted. ********
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...
[s6-init] ensuring user provided files have correct perms...
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
******** Please use the file wg3-cron to adjust the scheduled time for running WebGrab++. wg-cron can now be deleted. ********
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

Cannot make/remove an entry for the specified session
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...
[s6-init] ensuring user provided files have correct perms...
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

**Comment by j0nnymoe** [comment]
Please provide the information asked for in the issue template - were unable to help troubleshooting the issue without this.

**Comment by B0ndo2** [comment]
Updated

**Comment by tobbenb** [comment]
This would be either a podman issue or RHEL issue. There shouldn't be any need to configure anything PAM related.

**Comment by B0ndo2** [comment]
but modifying pam makes it work and I want to make it persistent

**Comment by j0nnymoe** [comment]
When used with docker it runs fine. It's either podman and/or something on RHEL causing the problem, SELinux maybe?

**Comment by B0ndo2** [comment]
SELinux is permissive. Let's assume it is a RHEL issue, is there a way to fix this so you add support for RHEL ?. Will this change break other distros ?

**Comment by tobbenb** [comment]
It's probably something you have to fix on your host.
We don't test anything using podman and we do not have any plans to support it. If it works, great. If it doesn't, sorry.

**Comment by B0ndo2** [comment]
let me run docker and test it to rule out Podman (or not), if it is RHEL issue, would you fix it ?

**Comment by B0ndo2** [comment]
I confirm it is Podman which is causing the problem
