### ISSUE TITLE
xmltv_time_modify.exe tool

### ISSUE THREAD

**Issue by B0ndo2** [linuxserver/docker-webgrabplus#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

xmltv_time_modify.exe is a mono based tool that allows modifying XMLTV time, can you add it to the image ?
https://github.com/harrygg/xmltv_time_modify
------------------------------

## Desired Behavior

Modify time in XMLTV
## Current Behavior

Tool not available
## Alternatives Considered

https://github.com/harrygg/xmltv_time_modify

**Comment by tobbenb** [comment]
Adding a 5 year old software that has limited info and doesn't really have much to do with this container other than XMLTV format is a no go.
