### ISSUE TITLE
Update to 3.1.6

### ISSUE THREAD

**Issue by Chris230291** [linuxserver/docker-webgrabplus#36]
Can we update to 3.1.6 please?
http://webgrabplus.com/download/sw

**Comment by tobbenb** [comment]
We really need to get this build triggered.

I'll bump the version when I have some time.

**Comment by Chris230291** [comment]
Is it not as simple as scraping the url above?

`curl -s http://webgrabplus.com/download/sw | grep -m1 "/download/sw/v" | sed 's/.*\/download\/sw\/v//g' | sed 's/".*//g'`

**Comment by tobbenb** [comment]
sed is the devil's work and I am too scared of it to try to understand it 😱
If the above work, I'll see if I can get it working in the build.

**Comment by Chris230291** [comment]
I'm not sure if its the best way, but it definitely works.
