### ISSUE TITLE
v3.1.8 'netstandard' error

### ISSUE THREAD

**Issue by pbathuk** [linuxserver/docker-webgrabplus#42]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When running the latest compiled docker I get an error message :
```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'WG.Common.InvalidSyntaxException:_MessageList' (3) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'WG.Common.InvalidSyntaxException:_MessageList' (3) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
```

The process will not run and therefore v.3.1.8 is currently broken.

I have also raise on webgrabplus forum : http://webgrabplus.com/content/v-318-netstandard-error

------------------------------

## Expected Behavior
standard process to run as normal.

## Current Behavior
error message

## Steps to Reproduce
1. run docker for v3.1.8
2. exec into the docker
3. run: `/bin/bash /defaults/update.sh`
4. see error

## Environment
**OS:** Ubuntu 20.4 LTS running docker
**CPU architecture:** x86_64
**How docker service was installed:** Official docker script and loaded docker-compose on top.

## Command used to create docker container (run/create/compose/screenshot)
```
  webgrabplus:
    image: linuxserver/webgrabplus:latest
    container_name: webgrabplus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/webgrabplus:/config
      - /opt/tvheadend/data:/data
    restart: unless-stopped
```

**Comment by aptalca** [comment]
Did you not test it locally before you PRed the 3.18 update? https://github.com/linuxserver/docker-webgrabplus/pull/41

**Comment by pbathuk** [comment]
I did not sorry, but I don't have a way to run mono without running in docker. 
So could only run the windows machine on windows, which I can do now and will see if I get the same error.
Give me a few mins

**Comment by pbathuk** [comment]
windows version, on windows 10, runs fine (well I get a hardware mis-match error) but it is processing.

**Comment by pbathuk** [comment]
I believe the reason for the failure is that it is asking for mono-complete : http://webgrabplus.com/documentation/installation/linux#install_linux_install

> See the mono documentation on how to install mono for different linux distros. Just be sure to actually install mono-complete, so use
> 
> sudo apt-get install mono-complete
> instead of
> sudo apt-get install mono-devel
> that is used on the mono site

I know later is says it should work, but then it does go on to say if you get an error to use mono-complete.
I wonder if with the change to the .net framework that is being processed if there are other parts of the mono framework needed, but complete will resolve?

not knowing much about mono etc I am happy to be guided on what is best & how to resolve

**Comment by tobbenb** [comment]
If mono complete is needed, webgraplus+ changed something in their build. Installing mono complete will increase the image size by quite a lot if I remember correctly. I'll see if there are any mono packages that might resolve the issue.

**Comment by tobbenb** [comment]
@pbathuk Could you please try to remove your container and pull a fresh one and then do the below command inside the container and see if that works?

`
apt update
apt install mono-reference-assemblies-2.0 
`

**Comment by pbathuk** [comment]
will do. I'm just waiting for it to process todays run, so will be a little while, but will do it asap

**Comment by pbathuk** [comment]
ok so I ran
```
apt update && apt install mono-reference-assemblies-2.0
```
on a fresh 3.1.8 docker container
and get the exact same message. (do I need to restart the container at all after install? - I didn't but not sure if I need to)

**Comment by tobbenb** [comment]
I don't think you need to restart the container.

Could you test adding mono-devel and see if that works?

**Comment by pbathuk** [comment]
I will do, I am just testing mono-complete just to see if it actually resolves it - if that does not work then its a fault with the package over the mono install. 
I'll then remove the container and do the mono-devel

**Comment by pbathuk** [comment]
ok can confirm that mono-complete does fix it.. however yes that padded up the container ALOT. 
Going to try the mono-devel now

**Comment by pbathuk** [comment]
mono-devel fixed it as well
on a new docker container I ran : 
```
/bin/bash /defaults/update.sh /* to prove it was still broken */
apt update && apt install mono-devel 
/bin/bash /defaults/update.sh /* to prove it was fixed */
```

**Comment by pbathuk** [comment]
on a separate note the following packages were flagged as being upgradable :
```
liblz4-1/bionic-updates,bionic-security 0.0~r131-2ubuntu3.1 amd64 [upgradable from: 0.0~r131-2ubuntu3]
libpam-modules/bionic-updates 1.1.8-3.6ubuntu2.18.04.3 amd64 [upgradable from: 1.1.8-3.6ubuntu2.18.04.2]
libpam-modules-bin/bionic-updates 1.1.8-3.6ubuntu2.18.04.3 amd64 [upgradable from: 1.1.8-3.6ubuntu2.18.04.2]
libpam-runtime/bionic-updates 1.1.8-3.6ubuntu2.18.04.3 all [upgradable from: 1.1.8-3.6ubuntu2.18.04.2]
libpam0g/bionic-updates 1.1.8-3.6ubuntu2.18.04.3 amd64 [upgradable from: 1.1.8-3.6ubuntu2.18.04.2]
```
