### ISSUE TITLE
After the last update, the license download does not work.

### ISSUE THREAD

**Issue by FloydKulis** [linuxserver/docker-webgrabplus#45]
I have webgrabplusplus in the docker on Synology NAS, after the last UpDate, unfortunately the webgrab does not work. 
I tried to delete WebGrab completely and installed a completely new copy. Unfortunately, nothing helped. Everything was working before the last update.

My messages:

[ ]
[ ] WebGrab+Plus/w MDB & REX Postprocess -- version V3.2.1.0
[ ]
[ ] Jan van Straaten
[ ] Francis De Paemeleere
[ ]
[ ] thanks to Paul Weterings and all the contributing users
[ ] --------------------------------------------------------------------------------
[ ]
[ ] Job started at 14/08/2021 20:20:01
[ Debug ]
[ Debug ] Running on: Unix 4.4.180.0
[ Debug ] Environment: 4.0.30319.42000
[ Debug ] Mono version: 6.12.0.122 (tarball Mon Feb 22 17:29:18 UTC 2021)
[ Debug ]
[ Debug ] Loading timezone data
[ Debug ] Embedded timezones source: timezone.timezonesdata.txt
[ Debug ] Reading config file: /config/WebGrab++.config.xml
[ Info ] Checking License ..
[ Info ] For License request/update data, see WGLicense.log.txt
[ ] Job finished at 14/08/2021 20:20:01 done in 0s
[Critical]
Object reference not set to an instance of an object
[Critical]
at  . ..ctor (System.String ) [0x01381] in <****>:0
at  .―.  (System.String[] ) [0x00351] in <****>:0
[Critical] Unhandled Exception
[Critical] For detailed info, see log file /config/WebGrab++.log.txt
[Critical] Execution stopped

Licence file:
[ ] WebGrab++ license request and update log
[ ] 2021/08/14 20:20

From what I can see at least one more other person has this problem:
http://www.webgrabplus.com/content/error-after-updating-v32

It says that on a different system with a different mono webgrab works.

**Comment by tobbenb** [comment]
Please fill out the issue template

**Comment by Laibalion** [comment]
@FloydKulis Lots of people seem to be having this issue. What worked for me, also using the LinuxServer WG++ image, was to set PUID and PGID to 0 (root). I'd prefer not do this, but I couldn't find any other way to solve this.
On the WG++ forums, there is also a discussion about this specific issue. Feel free to contribute to it.

**Comment by barzog** [comment]
According to discussion on webgrabplus forums there is an error in latest version of webgrabplus (starting from 3.2 and including 3.2.1), see http://webgrabplus.com/content/error-after-updating-v32
For me reverting to 3.1.8 (using pull ghcr.io/linuxserver/webgrabplus:version-V3.1.8) helped as suggested there http://webgrabplus.com/comment/26406#comment-26406

**Comment by Bl00d-B0b** [comment]
Hello,

same issue for me. webgrabplus support reccomend to update for new version, which is available:
27/11/2021
Version 3.2.3 beta
---------------------------------------------------------------------------------------------
- (3.2.2.5) improved: in mdb .. when actors and mdb-actors are combined, the remove duplicates didn't work correctly 
                        when one of them contained (role=..) 
- (3.2.2.4) fixed   : wrong implementation in times of the cultureinfo when a datetime pattern is used in start, stop or date
- (3.2.2.3) fixed   : missing value for stringmach in rex added (needed for removeduplicates of multi value elements like actor)
- (3.2.2.2) fixed   : operation maxelements failed after first show, element separator was not reinserted properly
- (3.2.2.1) fixed   : recently some websites have no value for ContentEncoding in the respones while still compressed.
                        to decompress the stream , specify the compression in the siteini site line e.g compression=gz

[https://github.com/SilentButeo2/webgrabplus-siteinipack/tree/master/evaluation-builds](url)

**Comment by aptalca** [comment]
I don't see 3.2.3 beta on their downloads page: http://webgrabplus.com/download/sw
We pull the releases from there

**Comment by Bl00d-B0b** [comment]
Hello,

maybe it's possible to use this:
https://github.com/SilentButeo2/webgrabplus-siteinipack/tree/master/evaluation-builds

P.S. also in docker you need to set fixed mac address, to not have problem with hardware_id license!

Ed
