### ISSUE TITLE
New Version 3.2.2 Beta

### ISSUE THREAD

**Issue by G1zm0** [linuxserver/docker-webgrabplus#46]
Can somebody upgrade to 3.2.2 beta?

I have the issue with webgrabplus that it crashes. Hopefully the new release fixes this issue
http://webgrabplus.com/download/sw/v3.2.2

**Comment by Olivier6767** [comment]
Any ETA yet for the update to 3.2.2?

**Comment by G1zm0** [comment]
Looks like this is a lost case...

**Comment by j0nnymoe** [comment]
More than welcome to submit a PR to help speed up the process.
