### ISSUE TITLE
How to run ubdate.sh from version 4.2.2-ls142?

### ISSUE THREAD

**Issue by FloydKulis** [linuxserver/docker-webgrabplus#53]
after updating to version 4.2.2-ls142 the command stopped working:
docker exec -i webgrabplus / bin / bash /defaults/update.sh

Receives the log:

/defaults/update.sh: line 3: cd: /app/wg++/bin: No such file or directory

Does anyone know how webgrabplus starts now?

**Comment by TheSpad** [comment]
The upstream project switched from mono to .net core so the container needs changes to support it, which we're working on. In the meantime stick with v3.2.3.

**Comment by FloydKulis** [comment]
It works!
