### ISSUE TITLE
v3.2.2 default non-root user => Unhandled Exceptioj

### ISSUE THREAD

**Issue by bugsyb** [linuxserver/docker-webgrabplus#54]
Fresh deployment of v3.2.2 results in error as below most probably related to non-root user privileges.
Running same command with root user works fine.
Container was re-deployed to make sure that it has a fresh start and privileges were checked on /config folder - all seemed to be ok.
Additional effort was made to discover if there's privileges error using strace, but didn't bring any additional details.

Container was created with:
```
docker run -it -v /tmp/webgrab/config:/config -v /tmp/webgrab/data:/data -e PUID=1000 -e PGID=1000 -e TZ=Europe/London --hostname wbtest2 --name wbtest2 lscr.io/linuxserver/webgrabplus:3.2.2
```

```
+ mono WebGrab+Plus.exe /config

            WebGrab+Plus/w MDB & REX Postprocess -- version V3.2.2.0            

                                Jan van Straaten                                
                             Francis De Paemeleere                              

            thanks to Paul Weterings and all the contributing users             
--------------------------------------------------------------------------------

Job started at 30/03/2022 14:15:38
Checking License ..
For License request/update data, see WGLicense.log.txt
Job finished at 30/03/2022 14:15:39 done in 1s

Object reference not set to an instance of an object.

  at  . ..ctor (System.String ) [0x01381] in <dbc8abb986f1459491b3d3a8a8141c6d>:0 
  at  .―.  (System.String[] ) [0x00351] in <dbc8abb986f1459491b3d3a8a8141c6d>:0 
Unhandled Exception
For detailed info, see log file /config/WebGrab++.log.txt
Execution stopped
```

Environment:
- Docker Host architecture aarch64

**Comment by argoncoast** [comment]
I might be wrong but the most recent v3.2.2 builds were broken due to a change from mono to dotnet.  

The most recent 4.2.2 builds are working but you might want to roll back the v3.2.2 build a little (might be worth trying `3.2.2-ls140` or migrate to the newer version.

**Comment by TheSpad** [comment]
There are some known issues with older builds due to a frankly very weird design choice in wg++ that we only discovered and solved when we migrated the image to dotnet and 4.2.2.

**Comment by bugsyb** [comment]
Thank you, I'll give it a try.
