### ISSUE TITLE
perl programming

### ISSUE THREAD

**Issue by saeddd** [linuxserver/docker-webgrabplus#56]
hello.
I have updated the docker, I mainly use it for tvheadend, and it had a content type change script that was programmed in perl and processed after REX, I found it on the web.
I see that now perl doesn't work anymore, is there any possibility to create this content in some other way?

attached script

![image](https://user-images.githubusercontent.com/19262617/168492242-dbf914cf-c21a-4630-84aa-590da7b93920.png)

**Comment by j0nnymoe** [comment]
You can re-install perl into the container use the guide here to create a custom script. https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
