### ISSUE TITLE
It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by Reinschki** [linuxserver/docker-webgrabplus#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior

After updating from Release 4.2.4-ls160 to 5.0.1-ls160 I get the command:
`sudo docker exec -it webgrabplus /bin/bash /defaults/update.sh`

this output:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      5.0.17 at [/app/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linux-x64
```
what's wrong?

## Steps to Reproduce

1. sudo docker exec -it webgrabplus /bin/bash /defaults/update.sh
2.
3.
4.

## Environment
**OS: Ubuntu 20.04.5 LTS /  Docker 20.10.8
**CPU architecture:** x86_64
**How docker service was installed: Docker 20.10.8

**Comment by aahmyu** [comment]
Yeah, broken for me as well with the same error.

**Comment by cilgor** [comment]
To manually install .NET 6.0 runtime, terminal in to your container and run the following commands:
```
wget https://dot.net/v1/dotnet-install.sh
bash dotnet-install.sh -c 6.0 --install-dir /app/dotnet --runtime dotnet
```

**Comment by Reinschki** [comment]
Do I understand correctly that this measure is only a fix to be able to use the release. The container should bring all that with it. Right?

**Comment by cilgor** [comment]
Yes, this is just a temporary measure to get your current container "working" until properly addressed in a future release.

**Comment by aptalca** [comment]
Can you guys test this image and let us know if it works?
`lspipepr/webgrabplus:5.0.1-pkg-c8de2cd3-pr-59`

It's a rebase to alpine 3.16, and update to s6v3 and dotnet 6

**Comment by cilgor** [comment]
@aptalca I tested `lspipepr/webgrabplus:5.0.1-pkg-c8de2cd3-pr-59` and it's working as expected. 

Attaching my test log  [WebGrab++.log.txt](https://github.com/linuxserver/docker-webgrabplus/files/9694283/WebGrab%2B%2B.log.txt)
