### ISSUE TITLE
wg3-cron and /defaults/update.sh missing

### ISSUE THREAD

**Issue by lswee** [linuxserver/docker-webgrabplus#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've just tried setting this up as new on my Raspberry Pi 3.

I could got the non-docker version working, but this container version seems to be missing config/wg3-cron and /defaults/update.sh

### Expected Behavior

Go into the container:
docker exec -it webgrabplus /bin/bash

There should be a cron file in config
There should be an update.sh in defaults

### Steps To Reproduce

Here's my compose file:

version: '3.5'
services:
  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest
    container_name: webgrabplus
    hostname: webgrabplus
    mac_address: 1:2:3:4:5:6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GB
    volumes:
      - ./webgrabplus/config:/config
      - ./webgrabplus/data:/data
    restart: unless-stopped

There's no cron file in the linked config folder

Also, going in (as above) shows these files missing.

This also doesn't work:
docker exec webgrabplus /defaults/update.sh

The file isn't found

### Environment

```markdown
Operating System: Debian GNU/Linux 11 (bullseye)
Docker version 24.0.7, build afdd53b
```

### CPU architecture

arm64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
docker logs webgrabplus
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by HDC67** [comment]
I am see a related issue I think. I now see an /app/update.sh but it id missing executable permissions:

```
root@webgrabplus:/# ls -la /app
total 4
drwxr-xr-x 1 abc  abc   38 Nov 19 11:11 .
drwxr-xr-x 1 root root 246 Nov 25 20:31 ..
drwxr-xr-x 1 abc  abc   96 Nov 19 11:13 dotnet
-rw-r--r-- 1 abc  abc  134 Nov 19 11:11 update.sh
drwxr-xr-x 1 abc  abc   34 Nov 19 11:13 wg++
root@webgrabplus:/# ls -la /defaults/
total 4
drwxr-xr-x 1 abc  abc    46 Nov 19 11:11 .
drwxr-xr-x 1 root root  246 Nov 25 20:31 ..
-rw-r--r-- 1 root root 1226 Nov 19 11:11 WebGrab++.config.xml
drwxr-xr-x 1 root root  172 Nov 19 11:15 ini
```

**Comment by VenimK** [comment]
> I am see a related issue I think. I now see an /app/update.sh but it id missing executable permissions:
> 
> ```
> root@webgrabplus:/# ls -la /app
> total 4
> drwxr-xr-x 1 abc  abc   38 Nov 19 11:11 .
> drwxr-xr-x 1 root root 246 Nov 25 20:31 ..
> drwxr-xr-x 1 abc  abc   96 Nov 19 11:13 dotnet
> -rw-r--r-- 1 abc  abc  134 Nov 19 11:11 update.sh
> drwxr-xr-x 1 abc  abc   34 Nov 19 11:13 wg++
> root@webgrabplus:/# ls -la /defaults/
> total 4
> drwxr-xr-x 1 abc  abc    46 Nov 19 11:11 .
> drwxr-xr-x 1 root root  246 Nov 25 20:31 ..
> -rw-r--r-- 1 root root 1226 Nov 19 11:11 WebGrab++.config.xml
> drwxr-xr-x 1 root root  172 Nov 19 11:15 ini
> ```
> 
> So yeah that's the problem. update.sh was moved to /app and wg3-cron was removed and replaced by /etc/crontabs/abc. So main issue is the lack of execute permissions. See merge commit: [a742267](https://github.com/linuxserver/docker-webgrabplus/commit/a742267bc975fc782ae01e6ec7afdef8e9694a70)

Yes, Same Problem here :(

**Comment by morpheus302** [comment]
same problem here. please add this to the wiki as it's obsolete as of right now

**Comment by dariusaurius** [comment]
You can work around this, by mounting this file in your docker-compose volumes and give execute permissions in the hosts filesystem with `chmod o+x ./app/update.sh`

>     volumes:
>       - ./app/update.sh:/app/update.sh
>       - ./config:/config
>       - ./data:/data
>       - ./etc/crontabs/abc:/etc/crontabs/abc

**Comment by ess2k** [comment]
Thanks to @dariusaurius I have resolved this issue. Just wanted to ask, with no documentation or communication of this change, is this a temp change as a test, and is it expected to change again and therefore break again?
Thanks

**Comment by ess2k** [comment]
Hi,

I have tried the suggested fixes above but for some reason my cronjob is now running automatically, here is my DC file,

```
version: "2.1"
services:
  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest
    container_name: webgrabplus
    hostname: webgrabplus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/DATA/webgrabplus/config:/config
      - /mnt/DATA/tvheadend/config/data:/data
      - /mnt/DATA/webgrabplus/xtra/update.sh:/app/update.sh
      - /mnt/DATA/webgrabplus/xtra/root:/etc/crontabs/root
#      - /mnt/DATA/webgrabplus/xtra/abc:/etc/crontabs/abc
    restart: unless-stopped
```

I have tried with and without abc mapped, and PGID, PUID set as 0, and still same issue,  I get the following error in the log,

```
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
crontab: can't move 'root.new' to 'root': Resource busy
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
If I run '/bin/bash /app/update.sh' manually in the console it works fine. Any help would be greatly appreciates.

**Comment by j0nnymoe** [comment]
Remove the additional lines you've added that aren't in the readme, we fixed what was needed in the newest image.

**Comment by Daniel-WW** [comment]
Same issue here: 
[custom-init] No custom files found, skipping...
I already installed the newest image.

**Comment by adrianmihalko** [comment]
I have another problem with latest image:

```
root@webgrabplus:/app# /app/dotnet/dotnet "WebGrab+Plus.dll" "/config"
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'WebGrab+Plus.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```
