### ISSUE TITLE
[Rex Update] Please Update Rex

### ISSUE THREAD

**Issue by Nitaro209** [linuxserver/docker-webgrabplus#72]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Current Rex Version is 3.2.5. 
Version 5.1.x is being discussed in the webgrabplus forum. It looks like the version here is out of date.

### Reason for change

Version 3.2.5 also causes errors:
[        ] Job finished at 04/05/2024 03:14:43 done in 12m 42s
[  Info  ] Job (REX Version: 3.2.5) started at 04/05/2024 03:14:43
[  Info  ] Starting REX Postprocess
[Critical] 
Value cannot be null. (Parameter 'source')
[Critical] 
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at  .–. . (XmlNode,  ,  )
   at  .–. ()
   at  .–..ctor(String[])
   at  .—. (String[])
[Critical] Unhandled Exception
[Critical] Execution stopped

**Comment by Roxedus** [comment]
We do not install Rex. From what i gather this was a bug in sitepack(?) so you might have to wipe `/config/siteini.pack` in order to get the new one.
