### ISSUE TITLE
Add xmltv_time_modify.exe to /app/wg++/bin.net

### ISSUE THREAD

**Issue by FloydKulis** [linuxserver/docker-webgrabplus#75]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Good morning, can I ask you to add a script to xmltv_time_modify.exe to /app/wg++/bin.net
https://github.com/SilentButeo2/webgrabplus-siteinipack/tree/master/postprocess_plugins/xmltv_time_modify

### Reason for change

Plungin is used to change the time in XML files. Unfortunately, Plex does not support time shift:
https://forums.plex.tv/t/own-epg-in-plex-do-not-work-time-shif-0200/880367/4
Plungin, according to the webgrabplusplus forum, is the solution to these problems:
http://webgrabplus.com/comment/35995#comment-35995

**Comment by j0nnymoe** [comment]
You're able to add this yourself via scripts as explained here: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by FloydKulis** [comment]
Unfortunately, the plugin added to the webgrab config gives the following error:

```
Job (/custom-services.d/xmltv_time_modify.exe /in:epg.xml /out:epg_local.xml /correction:local) started at 28/06/2024 20:23:04
Exception An error occurred trying to start process '/custom-services.d/xmltv_time_modify.exe' with working directory '/app/wg++/bin.net'. Exec format error
Job (/custom-services.d/xmltv_time_modify.exe /in:epg.xml /out:epg_local.xml /correction:local) finished at 28/06/2024 20:23:04 done in 0s
```

**Comment by thespad** [comment]
Assuming you're talking about this https://github.com/harrygg/xmltv_time_modify, it's 8 years since it was last updated and it requires .NET 4.5 (not core), which means you'd need to get mono installed in the container and possibly compile from source if it has any gcc linking.
