### ISSUE TITLE
Cron fails on my Synology ds916+ 

### ISSUE THREAD

**Issue by smurfster** [linuxserver/docker-webgrabplus#9]
I havent changed the wg-cron file at all. I have run "s6-setuidgid abc /bin/bash /defaults/update.sh" from the shell and it works fine. All I receive in the docker logs is "System Error" when the schedule runs.

I cant see any other problems

**Comment by j0nnymoe** [comment]
Unfortunately this isn't something we can test as no one within the team has synology hardware. We get reports from other issues on Syno hardware aswell and we believe this is due to them running an 18month old version of docker.

**Comment by homerr** [comment]
As this seems to be a Syno specific issue and we're unable to offer a fix I will close this.
